analyzer:
  errors:
    strict_top_level_inference: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true  
    prefer_const_constructors: true
    prefer_const_declarations: true